var OA_output = new Array(); 
OA_output['1'] = '';
OA_output['1'] += "<"+"span><"+"script type=\'text/javascript\'><"+"!--// <"+"![CDATA[\n";
OA_output['1'] += "/* openads=http://simplyguide.com/k/www/delivery bannerid=7 zoneid=5 source= */\n";
OA_output['1'] += "// ]]> --><"+"/script><"+"script type=\"text/javascript\"><"+"!--\n";
OA_output['1'] += "google_ad_client = \"ca-pub-7825705102693166\";\n";
OA_output['1'] += "/* cyberciti.biz-top 728x90 */\n";
OA_output['1'] += "google_ad_slot = \"3400670370\";\n";
OA_output['1'] += "google_ad_width = 728;\n";
OA_output['1'] += "google_ad_height = 90;\n";
OA_output['1'] += "//-->\n";
OA_output['1'] += "<"+"/script>\n";
OA_output['1'] += "<"+"script type=\"text/javascript\"\n";
OA_output['1'] += "src=\"http://pagead2.googlesyndication.com/pagead/show_ads.js\">\n";
OA_output['1'] += "<"+"/script><"+"script type=\'text/javascript\' src=\'http://simplyguide.com/k/www/delivery/ag.php\'><"+"/script><"+"/span><"+"div id=\'beacon_e74a87011d\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://simplyguide.com/k/www/delivery/lg.php?bannerid=7&amp;campaignid=3&amp;zoneid=5&amp;loc=1&amp;referer=http%3A%2F%2Fwww.cyberciti.biz%2Ffaq%2Fopen-a-pdf-file-under-linuxfreebsd%2F&amp;cb=e74a87011d\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['2'] = '';
OA_output['2'] += "<"+"span><"+"script type=\'text/javascript\'><"+"!--// <"+"![CDATA[\n";
OA_output['2'] += "/* openads=http://simplyguide.com/k/www/delivery bannerid=8 zoneid=6 source= */\n";
OA_output['2'] += "// ]]> --><"+"/script><"+"script type=\"text/javascript\"><"+"!--\n";
OA_output['2'] += "google_ad_client = \"ca-pub-7825705102693166\";\n";
OA_output['2'] += "/* Cyberciti.biz-300x250 */\n";
OA_output['2'] += "google_ad_slot = \"7895531150\";\n";
OA_output['2'] += "google_ad_width = 300;\n";
OA_output['2'] += "google_ad_height = 250;\n";
OA_output['2'] += "//-->\n";
OA_output['2'] += "<"+"/script>\n";
OA_output['2'] += "<"+"script type=\"text/javascript\"\n";
OA_output['2'] += "src=\"http://pagead2.googlesyndication.com/pagead/show_ads.js\">\n";
OA_output['2'] += "<"+"/script><"+"script type=\'text/javascript\' src=\'http://simplyguide.com/k/www/delivery/ag.php\'><"+"/script><"+"/span><"+"div id=\'beacon_f5f9afda21\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://simplyguide.com/k/www/delivery/lg.php?bannerid=8&amp;campaignid=3&amp;zoneid=6&amp;loc=1&amp;referer=http%3A%2F%2Fwww.cyberciti.biz%2Ffaq%2Fopen-a-pdf-file-under-linuxfreebsd%2F&amp;cb=f5f9afda21\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['3'] = '';
OA_output['3'] += "<"+"span><"+"script type=\'text/javascript\'><"+"!--// <"+"![CDATA[\n";
OA_output['3'] += "/* openads=http://simplyguide.com/k/www/delivery bannerid=8 zoneid=6 source= */\n";
OA_output['3'] += "// ]]> --><"+"/script><"+"script type=\"text/javascript\"><"+"!--\n";
OA_output['3'] += "google_ad_client = \"ca-pub-7825705102693166\";\n";
OA_output['3'] += "/* Cyberciti.biz-300x250 */\n";
OA_output['3'] += "google_ad_slot = \"7895531150\";\n";
OA_output['3'] += "google_ad_width = 300;\n";
OA_output['3'] += "google_ad_height = 250;\n";
OA_output['3'] += "//-->\n";
OA_output['3'] += "<"+"/script>\n";
OA_output['3'] += "<"+"script type=\"text/javascript\"\n";
OA_output['3'] += "src=\"http://pagead2.googlesyndication.com/pagead/show_ads.js\">\n";
OA_output['3'] += "<"+"/script><"+"script type=\'text/javascript\' src=\'http://simplyguide.com/k/www/delivery/ag.php\'><"+"/script><"+"/span><"+"div id=\'beacon_0b18b3fe84\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://simplyguide.com/k/www/delivery/lg.php?bannerid=8&amp;campaignid=3&amp;zoneid=6&amp;loc=1&amp;referer=http%3A%2F%2Fwww.cyberciti.biz%2Ffaq%2Fopen-a-pdf-file-under-linuxfreebsd%2F&amp;cb=0b18b3fe84\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['4'] = '';
OA_output['4'] += "<"+"span><"+"script type=\'text/javascript\'><"+"!--// <"+"![CDATA[\n";
OA_output['4'] += "/* openads=http://simplyguide.com/k/www/delivery bannerid=7 zoneid=5 source= */\n";
OA_output['4'] += "// ]]> --><"+"/script><"+"script type=\"text/javascript\"><"+"!--\n";
OA_output['4'] += "google_ad_client = \"ca-pub-7825705102693166\";\n";
OA_output['4'] += "/* cyberciti.biz-top 728x90 */\n";
OA_output['4'] += "google_ad_slot = \"3400670370\";\n";
OA_output['4'] += "google_ad_width = 728;\n";
OA_output['4'] += "google_ad_height = 90;\n";
OA_output['4'] += "//-->\n";
OA_output['4'] += "<"+"/script>\n";
OA_output['4'] += "<"+"script type=\"text/javascript\"\n";
OA_output['4'] += "src=\"http://pagead2.googlesyndication.com/pagead/show_ads.js\">\n";
OA_output['4'] += "<"+"/script><"+"script type=\'text/javascript\' src=\'http://simplyguide.com/k/www/delivery/ag.php\'><"+"/script><"+"/span><"+"div id=\'beacon_5231ff668f\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://simplyguide.com/k/www/delivery/lg.php?bannerid=7&amp;campaignid=3&amp;zoneid=5&amp;loc=1&amp;referer=http%3A%2F%2Fwww.cyberciti.biz%2Ffaq%2Fopen-a-pdf-file-under-linuxfreebsd%2F&amp;cb=5231ff668f\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['5'] = '';
OA_output['5'] += "<"+"span><"+"script type=\'text/javascript\'><"+"!--// <"+"![CDATA[\n";
OA_output['5'] += "/* openads=http://simplyguide.com/k/www/delivery bannerid=7 zoneid=5 source= */\n";
OA_output['5'] += "// ]]> --><"+"/script><"+"script type=\"text/javascript\"><"+"!--\n";
OA_output['5'] += "google_ad_client = \"ca-pub-7825705102693166\";\n";
OA_output['5'] += "/* cyberciti.biz-top 728x90 */\n";
OA_output['5'] += "google_ad_slot = \"3400670370\";\n";
OA_output['5'] += "google_ad_width = 728;\n";
OA_output['5'] += "google_ad_height = 90;\n";
OA_output['5'] += "//-->\n";
OA_output['5'] += "<"+"/script>\n";
OA_output['5'] += "<"+"script type=\"text/javascript\"\n";
OA_output['5'] += "src=\"http://pagead2.googlesyndication.com/pagead/show_ads.js\">\n";
OA_output['5'] += "<"+"/script><"+"script type=\'text/javascript\' src=\'http://simplyguide.com/k/www/delivery/ag.php\'><"+"/script><"+"/span><"+"div id=\'beacon_e1e5563891\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://simplyguide.com/k/www/delivery/lg.php?bannerid=7&amp;campaignid=3&amp;zoneid=5&amp;loc=1&amp;referer=http%3A%2F%2Fwww.cyberciti.biz%2Ffaq%2Fopen-a-pdf-file-under-linuxfreebsd%2F&amp;cb=e1e5563891\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['6'] = '';
OA_output['6'] += "<"+"span><"+"script type=\'text/javascript\'><"+"!--// <"+"![CDATA[\n";
OA_output['6'] += "/* openads=http://simplyguide.com/k/www/delivery bannerid=8 zoneid=6 source= */\n";
OA_output['6'] += "// ]]> --><"+"/script><"+"script type=\"text/javascript\"><"+"!--\n";
OA_output['6'] += "google_ad_client = \"ca-pub-7825705102693166\";\n";
OA_output['6'] += "/* Cyberciti.biz-300x250 */\n";
OA_output['6'] += "google_ad_slot = \"7895531150\";\n";
OA_output['6'] += "google_ad_width = 300;\n";
OA_output['6'] += "google_ad_height = 250;\n";
OA_output['6'] += "//-->\n";
OA_output['6'] += "<"+"/script>\n";
OA_output['6'] += "<"+"script type=\"text/javascript\"\n";
OA_output['6'] += "src=\"http://pagead2.googlesyndication.com/pagead/show_ads.js\">\n";
OA_output['6'] += "<"+"/script><"+"script type=\'text/javascript\' src=\'http://simplyguide.com/k/www/delivery/ag.php\'><"+"/script><"+"/span><"+"div id=\'beacon_7b61c57e25\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://simplyguide.com/k/www/delivery/lg.php?bannerid=8&amp;campaignid=3&amp;zoneid=6&amp;loc=1&amp;referer=http%3A%2F%2Fwww.cyberciti.biz%2Ffaq%2Fopen-a-pdf-file-under-linuxfreebsd%2F&amp;cb=7b61c57e25\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['7'] = '';

OA_output['8'] = '';

OA_output['16'] = '';

OA_output['17'] = '';

OA_output['18'] = '';

OA_output['19'] = '';

OA_output['20'] = '';

OA_output['21'] = '';

OA_output['22'] = '';

OA_output['23'] = '';
OA_output['23'] += "<"+"span><"+"script type=\'text/javascript\'><"+"!--// <"+"![CDATA[\n";
OA_output['23'] += "/* openads=http://simplyguide.com/k/www/delivery bannerid=34 zoneid=23 source= */\n";
OA_output['23'] += "// ]]> --><"+"/script><"+"script type=\"text/javascript\"><"+"!--\n";
OA_output['23'] += "google_ad_client = \"ca-pub-7825705102693166\";\n";
OA_output['23'] += "/* Cyberciti.biz Right 160x600 */\n";
OA_output['23'] += "google_ad_slot = \"3456420484\";\n";
OA_output['23'] += "google_ad_width = 160;\n";
OA_output['23'] += "google_ad_height = 600;\n";
OA_output['23'] += "//-->\n";
OA_output['23'] += "<"+"/script>\n";
OA_output['23'] += "<"+"script type=\"text/javascript\"\n";
OA_output['23'] += "src=\"http://pagead2.googlesyndication.com/pagead/show_ads.js\">\n";
OA_output['23'] += "<"+"/script><"+"script type=\'text/javascript\' src=\'http://simplyguide.com/k/www/delivery/ag.php\'><"+"/script><"+"/span><"+"div id=\'beacon_695a5df39b\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://simplyguide.com/k/www/delivery/lg.php?bannerid=34&amp;campaignid=3&amp;zoneid=23&amp;loc=1&amp;referer=http%3A%2F%2Fwww.cyberciti.biz%2Ffaq%2Fopen-a-pdf-file-under-linuxfreebsd%2F&amp;cb=695a5df39b\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['24'] = '';
OA_output['24'] += "<"+"span><"+"script type=\'text/javascript\'><"+"!--// <"+"![CDATA[\n";
OA_output['24'] += "/* openads=http://simplyguide.com/k/www/delivery bannerid=7 zoneid=5 source= */\n";
OA_output['24'] += "// ]]> --><"+"/script><"+"script type=\"text/javascript\"><"+"!--\n";
OA_output['24'] += "google_ad_client = \"ca-pub-7825705102693166\";\n";
OA_output['24'] += "/* cyberciti.biz-top 728x90 */\n";
OA_output['24'] += "google_ad_slot = \"3400670370\";\n";
OA_output['24'] += "google_ad_width = 728;\n";
OA_output['24'] += "google_ad_height = 90;\n";
OA_output['24'] += "//-->\n";
OA_output['24'] += "<"+"/script>\n";
OA_output['24'] += "<"+"script type=\"text/javascript\"\n";
OA_output['24'] += "src=\"http://pagead2.googlesyndication.com/pagead/show_ads.js\">\n";
OA_output['24'] += "<"+"/script><"+"script type=\'text/javascript\' src=\'http://simplyguide.com/k/www/delivery/ag.php\'><"+"/script><"+"/span><"+"div id=\'beacon_128f7b8522\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://simplyguide.com/k/www/delivery/lg.php?bannerid=7&amp;campaignid=3&amp;zoneid=5&amp;loc=1&amp;referer=http%3A%2F%2Fwww.cyberciti.biz%2Ffaq%2Fopen-a-pdf-file-under-linuxfreebsd%2F&amp;cb=128f7b8522\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['25'] = '';
OA_output['25'] += "<"+"span><"+"script type=\'text/javascript\'><"+"!--// <"+"![CDATA[\n";
OA_output['25'] += "/* openads=http://simplyguide.com/k/www/delivery bannerid=8 zoneid=6 source= */\n";
OA_output['25'] += "// ]]> --><"+"/script><"+"script type=\"text/javascript\"><"+"!--\n";
OA_output['25'] += "google_ad_client = \"ca-pub-7825705102693166\";\n";
OA_output['25'] += "/* Cyberciti.biz-300x250 */\n";
OA_output['25'] += "google_ad_slot = \"7895531150\";\n";
OA_output['25'] += "google_ad_width = 300;\n";
OA_output['25'] += "google_ad_height = 250;\n";
OA_output['25'] += "//-->\n";
OA_output['25'] += "<"+"/script>\n";
OA_output['25'] += "<"+"script type=\"text/javascript\"\n";
OA_output['25'] += "src=\"http://pagead2.googlesyndication.com/pagead/show_ads.js\">\n";
OA_output['25'] += "<"+"/script><"+"script type=\'text/javascript\' src=\'http://simplyguide.com/k/www/delivery/ag.php\'><"+"/script><"+"/span><"+"div id=\'beacon_2ef3ab1db7\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://simplyguide.com/k/www/delivery/lg.php?bannerid=8&amp;campaignid=3&amp;zoneid=6&amp;loc=1&amp;referer=http%3A%2F%2Fwww.cyberciti.biz%2Ffaq%2Fopen-a-pdf-file-under-linuxfreebsd%2F&amp;cb=2ef3ab1db7\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['26'] = '';
OA_output['26'] += "<"+"span><"+"script type=\'text/javascript\'><"+"!--// <"+"![CDATA[\n";
OA_output['26'] += "/* openads=http://simplyguide.com/k/www/delivery bannerid=38 zoneid=26 source= */\n";
OA_output['26'] += "// ]]> --><"+"/script><"+"script type=\"text/javascript\"><"+"!--\n";
OA_output['26'] += "google_ad_client = \"ca-pub-7825705102693166\";\n";
OA_output['26'] += "/* in.336x280_BTF_TextImagesRichMedia_UNIX_LInuxTechRelatedPages */\n";
OA_output['26'] += "google_ad_slot = \"0921116676\";\n";
OA_output['26'] += "google_ad_width = 336;\n";
OA_output['26'] += "google_ad_height = 280;\n";
OA_output['26'] += "//-->\n";
OA_output['26'] += "<"+"/script>\n";
OA_output['26'] += "<"+"script type=\"text/javascript\"\n";
OA_output['26'] += "src=\"http://pagead2.googlesyndication.com/pagead/show_ads.js\">\n";
OA_output['26'] += "<"+"/script><"+"script type=\'text/javascript\' src=\'http://simplyguide.com/k/www/delivery/ag.php\'><"+"/script><"+"/span><"+"div id=\'beacon_22c3b4aef5\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://simplyguide.com/k/www/delivery/lg.php?bannerid=38&amp;campaignid=3&amp;zoneid=26&amp;loc=1&amp;referer=http%3A%2F%2Fwww.cyberciti.biz%2Ffaq%2Fopen-a-pdf-file-under-linuxfreebsd%2F&amp;cb=22c3b4aef5\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
